apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: redis-auth
  labels:
    app.kubernetes.io/managed-by: {{ .Release.Service }}
spec:
  refreshInterval: {{ .Values.refreshInterval | quote }}
  secretStoreRef:
    name: {{ .Values.secretStore.name | quote }}
    kind: {{ .Values.secretStore.kind | quote }}
  target:
    name: redis-auth
    creationPolicy: Owner
  data:
    - secretKey: redis-password
      remoteRef:
        key: {{ .Values.redis.remoteKey | quote }}
        property: redis-password
